### PR TITLE
Consistent use of hgt_matrix_half. Delete delz in warm rain diagnostics.

### PR DESCRIPTION
**Pull request by alejandrobodas**
This pull request addresses #60 and deletes variable delz, which was not used by the warm rain diagnostics.

### CODE REVIEW

**Comment by RobertPincus** [comment]
@alejandrobodas This looks slick, thanks for addressing this so quickly. Should we not add some documentation to explain where the half-levels are defined?

**Comment by alejandrobodas** [comment]
Hi @brhillman , please could you do the review for this fix? Basically, I've dropped the TOA level from hgt_matrix_half because it wasn't used. Now the array contains the bottom levels. I don't set the surface to 0 in cosp2_test for two reasons:

- to avoid confusion in the implementation in models. This was done because in the input file from the UM the bottom layer interface is not the surface, so I had to overwrite it. I think it's better show how it should be done.
- to avoid breaking the regression tests by this small change in the description of the bottom layer.

Thanks!

**Comment by alejandrobodas** [comment]
Hi @RobertPincus , I was writing my previous comment when you sent yours! Thanks for looking into this. Yes, that's a good idea, where do you think this should be documented? One option is in the cosp2_test driver, which is the template people will follow to implement it in models, but I'm open to suggestions.

**Comment by RobertPincus** [comment]
@alejandrobodas In the driver, yes, but wouldn't it also be important to note it in the COSP interface, where the input variables are explained?

**Comment by alejandrobodas** [comment]
@RobertPincus I've added comments in those two places as suggested. If you're happy, I'll wait to hear from @brhillman before merging.

**Review by dustinswales — APPROVED** [review]
@alejandrobodas 
Thanks for cleaning up my mess so quickly!
My apologies for this, I can't recall why I had done it this way.

**Comment by alejandrobodas** [comment]
@dustinswales ha, ha, no worries. Given that we flipped the order of levels between COSP1 and COSP2 and the added confusion of having two height arrays with different number of levels, you did an excellent job!

**Comment by klein21** [comment]
Does it make sense to ask if someone has tested the fix in a GCM test case yet?
@brhillman<https://urldefense.us/v3/__https:/github.com/brhillman__;!!G2kpM7uM-TzIFchu!nH9zwqUfU4jH2NFX_DOxLcigkU4IlkikQFxCNtNIofmXG44HphL2gBnm1SEEVkTL7Q$>
@alejandrobodas<https://urldefense.us/v3/__https:/github.com/alejandrobodas__;!!G2kpM7uM-TzIFchu!n9jRsThK3aiZmjoko46P5nS6lPA-xs6ScgmxUM_KxQSIpJ2KEopFGJPCVfaTJYzg6g$>


From: dustinswales ***@***.***>
Reply-To: "CFMIP/COSPv2.0" ***@***.***>
Date: Tuesday, June 15, 2021 at 7:41 AM
To: "CFMIP/COSPv2.0" ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [CFMIP/COSPv2.0] Consistent use of hgt_matrix_half. Delete zlev in warm rain diagnostics. (#61)


@dustinswales approved this pull request.

@alejandrobodas<https://urldefense.us/v3/__https:/github.com/alejandrobodas__;!!G2kpM7uM-TzIFchu!nXPTiM9v6aMqcffTSzZIZjdDrOfIIjDoUJtcjUaGKxUV4X57NEUb2ekqlCEohKA4pw$>
Thanks for cleaning up my mess so quickly!
My apologies for this, I can't recall why I had done it this way.

**Comment by takmichibata** [comment]
@alejandrobodas @dustinswales I apologize for this bug in warm rain diagnostics. Thank you very much for fixing it.

**Comment by brhillman** [comment]
@alejandrobodas sorry I missed the review on this! Thanks for addressing this!

**Pull request merged**
