### PR TITLE
compiler package name change

### PR DESCRIPTION
**Pull request by rscohn2**

### CODE REVIEW

**Comment by RobertPincus** [comment]
@rscohn2 I don't know how we attracted your attention but thanks so much for this contribution. Note that the syntax for setting environment variables for Github actions has changed, which is why the tests are failing. The fix is straightforward: replace e.g. `echo "::set-env name=CC::nvc"` with `echo "CC::nvc" >> $GITHUB_ENV` in lines 131-133 and lines 140-142. 

We greatly appreciate being able to use oneAPI in the continuous integration. If you have suggestions or documentation as to how we can be more graceful or robust please let us know. 

Either I or @alejandrobodas might act as reviewers of the PR.

**Comment by rscohn2** [comment]
We are hopefully done with package name changes and I am searching github for old usages to help people  move forward. We are happy that you find the CI support useful. You can find samples at https://github.com/oneapi-src/oneapi-ci

**Comment by rscohn2** [comment]
Would it be possible for you to make the changes to the env variables? I am in the middle of fixing 30+ repos. You should be able to push to the same branch. Thanks.

**Comment by RobertPincus** [comment]
@rscohn2 I've updated the syntax and the compilers are now being used properly, so thanks very much. There is a failure in using the compilers to build the widely-used netCDF library, or rather in setting up the configuration. (The error arises in linking two files.)  Being able to build the netCDF Fortran library within the CI, and generally with the oneAPI, would be very useful for earth science applications. Have you found a solution in other repos?

**Comment by rscohn2** [comment]
There is an issue with ld in 18.04. 20.04 has the fix. Are you OK moving to a new ubuntu?

**Comment by rscohn2** [comment]
Moving to 20.04 broke gfortran build. I will ask if there is a solution for using 18.04.

**Comment by rscohn2** [comment]
I was given a workaround for the ld problem, but that has some problems. I was also told that ubuntu has released 18.04.04, which fixes the problem. It seems best to wait a few days and retry without the workaround. Hopefully github will update their 18.04 quickly.

**Comment by alejandrobodas** [comment]
Dear @rscohn2 , I've moved to ubuntu 20.04 and fixed the CI tests in #58. Thank you very much for your help. Closing this pull request.

**Pull request closed without merging**
