### PR TITLE
Changes to cosp error checking routine 

### PR DESCRIPTION
**Pull request by dustinswales**
I propose to merge some improvements onto the COSP2 master branch. 

1) Expanded error checking routine.
Background: Currently all inputs provided to COSP2 are passed to an error checking routine, where they undergo a basic sanity check before the simulators are called. If erroneous input values are encountered, the simulators which are dependent on those inputs are turned off, the requested diagnostics are set to fill values, and an error message is provided.
In CESM2, where RTTOV is not used, I had to comment out the checking of the RTTOV inputs, as they are not provided. This is less than ideal, as this requires a special installation of COSP2 in CESM2.
Solution: Expand the error checking routine to ensure that the correct inputs are provided for the requested diagnostics. This solution is general and extends to other COSP2 configurations.

2) Cleaned up initialization routine. Removed unused arguments from subroutine cosp_init.

### CODE REVIEW

**Comment by dustinswales** [comment]
Steve,

I scoped out updating to a more recent version of RTTOV for COSP2 (currently up to RTTOV12.2), but it turns out that the more recent versions of RTTOV are not backwards compatible with older versions. In a nutshell, it was quite a bit of work to bring COSP2 up-to-date with new versions of RTTOV, so we didn't. COSP2 is distributed using a stub for RTTOV, so the infrastructure is in place for someone to pick this up, but would require some work on their part. I'd say RTTOV is more out than in...
The arguments I removed from cosp_init were all for RTTOV9.3, which we decided awhile back to drop support for in COSP2.

Dustin

**Comment by klein21** [comment]
Dustin,

Thanks for explaining the current situation.

Steve

**Comment by RobertPincus** [comment]
Does anyone on the PMC know who the constituency for RTTOV is? Should we poll the user group? It sounds like the best course of action might be to nudge RTTOV all the way out the door… 

- Robert

**Comment by klein21** [comment]
If no one on the PMC makes a strong case for it, I would then favor asking the cosp-user group as the next step.

Maybe RTTOV need not be fully pushed out the door, but perhaps put in a closet that it is rarely opened (i.e. out of the way and not in need of any active attention).

**Comment by dustinswales** [comment]
@alejandrobodas 
Do you have any objections to this update on the master branch?

**Comment by alejandrobodas** [comment]
Hi @dustinswales I have no objections to these changes. However, I think the driver should also be updated and check the error messages. At the moment, if one implements COSP as it is done in the driver, the model won't stop if an error occurs, and since the error messages are not printed out as warnings, the user won't know why the diagnostics contain missing data.

Regarding RTTOV, I think we are pretty much in the position that @klein21 favours (once this change is merged).

**Comment by klein21** [comment]
I wasn’t favouring any position yet, but I am guessing Alejandro that you favour putting RTTOV “in the closet”?

**Comment by dustinswales** [comment]
@alejandrobodas 
I've added a few lines to the driver to print error messages when errors occur.

**Pull request merged**
